// LoginFrame.java
package finalyearproject;

import javax.swing.*;
import java.awt.*;

public class LoginFrame extends JFrame {
    private JTextField usernameField;
    private JPasswordField passwordField;

    public LoginFrame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() {
        // Initialize components
        usernameField = new JTextField(20);
        passwordField = new JPasswordField(20);
        JButton loginButton = new JButton("Login");

        // Set layout
        setLayout(new FlowLayout());

        // Add components
        add(new JLabel("Username:"));
        add(usernameField);
        add(new JLabel("Password:"));
        add(passwordField);
        add(loginButton);

        // Set frame properties
        setTitle("Login");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setLocationRelativeTo(null); // Center the frame
        setVisible(true);

        // Ensure frame is opaque
       // setOpaque(true);
        getContentPane().setBackground(Color.WHITE); // Set background color
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void login() {
        // Implement login logic here
        String username = usernameField.getText();
        String password = new String(passwordField.getPassword());

        // Example validation (replace with your own logic)
        if (username.equals("admin") && password.equals("admin")) {
            // Successful login, close the login frame and open main app
            dispose(); // Close login frame
            try {
                new MainApp().setVisible(true); // Open main app
            } catch (Exception ex) {
                ex.printStackTrace(); // Handle exception
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
public static void main(String[] args) {
        // Run login frame directly for testing
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame();
            }
        });
    }}
